#ifndef COLORBAR_PCIE_DRIVER_H
#define COLORBAR_PCIE_DRIVER_H

#include <linux/bits.h>
#include <linux/ioctl.h>
#include <linux/mm.h>
#include <linux/types.h>

#define COLORBAR_PCI_VENDOR_ID 0x0755
#define COLORBAR_PCI_DEVICE_ID 0x0755

#define COLORBAR_DEVICE_NAME "colorbar_pcie_rx"
#define COLORBAR_CLASS_NAME "colorbar_pcie"

#define COLORBAR_BAR_DEFAULT 1
#define COLORBAR_REG_DMA_ARM 0x100
#define COLORBAR_REG_DMA_START 0x104
#define COLORBAR_REG_DMA_LEN 0x108
#define COLORBAR_REG_DMA_ADDR 0x110
#define COLORBAR_REG_DMA_ADDR_ECHO0 0x114
#define COLORBAR_REG_DMA_ADDR_ECHO1 0x118
#define COLORBAR_REG_DMA_ADDR_ECHO2 0x11c
#define COLORBAR_REG_DMA_ADDR_ECHO3 0x120
#define COLORBAR_REG_DMA_STOP 0x130
#define COLORBAR_REG_DMA_STATUS 0x170
#define COLORBAR_REG_DMA_ACTIVE_ADDR 0x174
#define COLORBAR_REG_DMA_ACTIVE_LEN 0x178
#define COLORBAR_REG_DMA_BYTES_SENT 0x17c
#define COLORBAR_DMA_ARM_MAGIC 0xA55A5AA5u
#define COLORBAR_DMA_ALIGN_BYTES 64u
#define COLORBAR_DMA_STATUS_VERSION 0x0Au

#define COLORBAR_STATUS_BUSY BIT(0)
#define COLORBAR_STATUS_FRAME_DONE BIT(1)
#define COLORBAR_STATUS_IDLE BIT(2)
#define COLORBAR_STATUS_STOP_ACK BIT(3)
#define COLORBAR_STATUS_HOST_ARM BIT(4)
#define COLORBAR_STATUS_START_CMD_SEEN BIT(5)
#define COLORBAR_STATUS_DMA_ADDR_VALID BIT(6)
#define COLORBAR_STATUS_DMA_LEN_VALID BIT(7)
#define COLORBAR_STATUS_PCIE_DMA_ENABLE BIT(8)
#define COLORBAR_STATUS_ADDR_ERROR BIT(9)
#define COLORBAR_STATUS_LEN_ERROR BIT(10)
#define COLORBAR_STATUS_FIFO_OVERFLOW BIT(11)
#define COLORBAR_STATUS_FIFO_UNDERFLOW BIT(12)
#define COLORBAR_STATUS_STOP_PENDING BIT(13)
#define COLORBAR_STATUS_HOST_START BIT(14)
#define COLORBAR_STATUS_RC_CFG_EP BIT(15)
#define COLORBAR_STATUS_ERROR_MASK \
	(COLORBAR_STATUS_ADDR_ERROR | COLORBAR_STATUS_LEN_ERROR | \
	 COLORBAR_STATUS_FIFO_OVERFLOW | COLORBAR_STATUS_FIFO_UNDERFLOW)
#define COLORBAR_STATUS_VERSION(status) (((status) >> 24) & 0xff)

#define COLORBAR_WIDTH 1920u
#define COLORBAR_HEIGHT 1080u
#define COLORBAR_BYTES_PER_PIXEL 2u
#define COLORBAR_FRAME_SIZE (COLORBAR_WIDTH * COLORBAR_HEIGHT * COLORBAR_BYTES_PER_PIXEL)
#define COLORBAR_DMA_BUFFER_SIZE (4u * 1024u * 1024u)
#define COLORBAR_DMA_GUARD_SIZE (COLORBAR_DMA_BUFFER_SIZE - COLORBAR_FRAME_SIZE)
#define COLORBAR_DMA_MAX_BYTES COLORBAR_FRAME_SIZE
#define COLORBAR_BUFFER_COUNT 1u
#define COLORBAR_FORMAT_RGB565 0x00005651u
#define COLORBAR_BUFFER_SIZE COLORBAR_DMA_BUFFER_SIZE

#define COLORBAR_IOCTL_MAGIC 'C'

struct colorbar_rx_info {
	__u32 width;
	__u32 height;
	__u32 format;
	__u32 buffer_count;
	__u32 frame_size;
	__u32 buffer_size;
};

struct colorbar_frame_info {
	__u32 buffer_index;
	__u32 frame_counter;
	__u32 valid_size;
	__u32 flags;
};

#define COLORBAR_IOC_GET_INFO _IOR(COLORBAR_IOCTL_MAGIC, 0x00, struct colorbar_rx_info)
#define COLORBAR_IOC_ALLOC_BUFS _IO(COLORBAR_IOCTL_MAGIC, 0x01)
#define COLORBAR_IOC_START _IO(COLORBAR_IOCTL_MAGIC, 0x02)
#define COLORBAR_IOC_STOP _IO(COLORBAR_IOCTL_MAGIC, 0x03)
#define COLORBAR_IOC_WAIT_FRAME _IOR(COLORBAR_IOCTL_MAGIC, 0x04, struct colorbar_frame_info)
#define COLORBAR_IOC_FREE_BUFS _IO(COLORBAR_IOCTL_MAGIC, 0x05)
#define COLORBAR_IOC_SAFE_STOP _IO(COLORBAR_IOCTL_MAGIC, 0x06)

#endif
