#ifndef COLORBAR_PCIE_DRIVER_H
#define COLORBAR_PCIE_DRIVER_H

#include <linux/bits.h>
#include <linux/ioctl.h>
#include <linux/mm.h>
#include <linux/types.h>

#define COLORBAR_PCI_VENDOR_ID 0x0755
#define COLORBAR_PCI_DEVICE_ID 0x0755

#define COLORBAR_DEVICE_NAME "colorbar_pcie_rx"
#define COLORBAR_CLASS_NAME "colorbar_pcie"

#define COLORBAR_BAR_DEFAULT 1
#define COLORBAR_REG_DMA_ARM 0x100
#define COLORBAR_REG_DMA_START 0x104
#define COLORBAR_REG_DMA_LEN 0x108
#define COLORBAR_REG_DMA_ADDR 0x110
#define COLORBAR_REG_DMA_ADDR_ECHO0 0x114
#define COLORBAR_REG_DMA_ADDR_ECHO1 0x118
#define COLORBAR_REG_DMA_ADDR_ECHO2 0x11c
#define COLORBAR_REG_DMA_ADDR_ECHO3 0x120
#define COLORBAR_REG_DMA_STOP 0x130
#define COLORBAR_REG_DMA_STATUS 0x170
#define COLORBAR_DMA_ARM_MAGIC 0xA55A5AA5u
#define COLORBAR_DMA_MIN_BYTES 64u
#define COLORBAR_DMA_ALIGN_BYTES 64u

#define COLORBAR_STATUS_BUSY BIT(0)
#define COLORBAR_STATUS_FRAME_DONE BIT(1)
#define COLORBAR_STATUS_START_CMD_SEEN BIT(2)
#define COLORBAR_STATUS_ADDR_ERROR BIT(3)
#define COLORBAR_STATUS_HOST_ARM BIT(4)
#define COLORBAR_STATUS_HOST_START BIT(5)
#define COLORBAR_STATUS_PCIE_DMA_ENABLE BIT(6)
#define COLORBAR_STATUS_RC_CFG_EP BIT(7)
#define COLORBAR_STATUS_DMA_START_ADDR_VALID BIT(8)
#define COLORBAR_STATUS_DMA_LEN_VALID BIT(9)
#define COLORBAR_STATUS_FIXED_TEST_MODE BIT(10)

#define COLORBAR_WIDTH 1920u
#define COLORBAR_HEIGHT 1080u
#define COLORBAR_BYTES_PER_PIXEL 2u
#define COLORBAR_FRAME_SIZE (COLORBAR_WIDTH * COLORBAR_HEIGHT * COLORBAR_BYTES_PER_PIXEL)
#define COLORBAR_MARK_SIZE 64u
#define COLORBAR_BUFFER_COUNT 4u
#define COLORBAR_FORMAT_RGB565 0x00005651u
#define COLORBAR_BUFFER_SIZE PAGE_ALIGN(COLORBAR_FRAME_SIZE + COLORBAR_MARK_SIZE)

#define COLORBAR_IOCTL_MAGIC 'C'

struct colorbar_rx_info {
	__u32 width;
	__u32 height;
	__u32 format;
	__u32 buffer_count;
	__u32 frame_size;
	__u32 buffer_size;
};

struct colorbar_frame_info {
	__u32 buffer_index;
	__u32 frame_counter;
	__u32 valid_size;
	__u32 flags;
};

#define COLORBAR_IOC_GET_INFO _IOR(COLORBAR_IOCTL_MAGIC, 0x00, struct colorbar_rx_info)
#define COLORBAR_IOC_ALLOC_BUFS _IO(COLORBAR_IOCTL_MAGIC, 0x01)
#define COLORBAR_IOC_START _IO(COLORBAR_IOCTL_MAGIC, 0x02)
#define COLORBAR_IOC_STOP _IO(COLORBAR_IOCTL_MAGIC, 0x03)
#define COLORBAR_IOC_WAIT_FRAME _IOR(COLORBAR_IOCTL_MAGIC, 0x04, struct colorbar_frame_info)
#define COLORBAR_IOC_FREE_BUFS _IO(COLORBAR_IOCTL_MAGIC, 0x05)
#define COLORBAR_IOC_SAFE_STOP _IO(COLORBAR_IOCTL_MAGIC, 0x06)

#endif
